services:
  wagon:
    image: quay.io/akretion/docky-ruby:latest
    environment:
      - API_EMAIL=$API_EMAIL
      - API_KEY=$API_KEY
    volumes:
      - .:/workspace
      - $HOME/.docky/shared/bundle:/usr/local/bundle
    labels:
      docky.main.service: True
      docky.user: ubuntu
      traefik.wagon.frontend.rule: "Host:doc.dy"
      traefik.wagon.port: 3333
      traefik.enable: True
version: '3'
